[versions]
agp = "8.0.2"
compose-jb = "1.4.0-dev-wasm08"
kotlin = "1.9.0-dev-6976"
kotlinx-coroutines = "1.7.0-RC-wasm0"
kotlinx-serialization = "1.5.1-wasm0"
androidx-core-ktx = "1.10.1"
androidx-collection = "1.3.0-alpha04"
androidx-appcompat = "1.6.1"
androidx-exifinterface = "1.3.6"
spotless = "6.20.0"
ktlint = "0.48.2"
publish = "0.25.3"
dokka = "1.8.20"
moko-resources = "0.23.0"
ktor = "2.3.3-wasm0"
okio = "3.5.0"
uri-kmp = "0.0.13"
kermit = "2.0.0-RC4"
androidsvg = "1.4"
benchmark = "1.2.0-beta02"
junit = "4.13.2"
androidx-junit = "1.1.5"
uiautomator = "2.2.0"
profileinstaller = "1.3.1"
roborazzi = "1.5.0-alpha-3"
robolectric = "4.10.3"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
composeJb = { id = "org.jetbrains.compose", version.ref = "compose-jb" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
publish = { id = "com.vanniktech.maven.publish", version.ref = "publish" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
moko-resources = { id = "dev.icerock.mobile.multiplatform-resources", version.ref = "moko-resources" }
baselineProfile = { id = "androidx.baselineprofile", version.ref = "benchmark" }
androidTest = { id = "com.android.test", version.ref = "agp" }
roborazzi = { id = "io.github.takahirom.roborazzi", version.ref = "roborazzi" }

[libraries]
gradlePlugin-android = { module = "com.android.tools.build:gradle", version.ref = "agp" }
gradlePlugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
gradlePlugin-compose = { module = "org.jetbrains.compose:compose-gradle-plugin", version.ref = "compose-jb" }

kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core-ktx" }
androidx-collection = { module = "androidx.collection:collection", version.ref = "androidx-collection" }
androidx-appcompat = { module = "androidx.appcompat:appcompat-resources", version.ref = "androidx-appcompat" }
androidx-exifinterface = { module = "androidx.exifinterface:exifinterface", version.ref = "androidx-exifinterface" }

junit = { module = "junit:junit", version.ref = "junit" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-junit" }
androidx-uiautomator = { module = "androidx.test.uiautomator:uiautomator", version.ref = "uiautomator" }
androidx-benchmark-macro-junit4 = { module = "androidx.benchmark:benchmark-macro-junit4", version.ref = "benchmark" }
androidx-profileinstaller = { module = "androidx.profileinstaller:profileinstaller", version.ref = "profileinstaller" }

robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
roborazzi-core = { module = "io.github.takahirom.roborazzi:roborazzi", version.ref = "roborazzi" }
roborazzi-junit = { module = "io.github.takahirom.roborazzi:roborazzi-junit-rule", version.ref = "roborazzi" }
roborazzi-compose = { module = "io.github.takahirom.roborazzi:roborazzi-compose", version.ref = "roborazzi" }

okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
okio-fakefilesystem = { module = "com.squareup.okio:okio-fakefilesystem", version.ref = "okio" }

ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-js = { module = "io.ktor:ktor-client-js", version.ref = "ktor" }
ktor-client-js-js = { module = "io.ktor:ktor-client-js-js", version.ref = "ktor" }
ktor-client-js-wasm = { module = "io.ktor:ktor-client-js-wasm", version.ref = "ktor" }

uri-kmp = { module = "com.eygraber:uri-kmp", version.ref = "uri-kmp" }
moko-resources = { module = "dev.icerock.moko:resources", version.ref = "moko-resources" }
kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }
androidsvg = { module = "com.caverock:androidsvg-aar", version.ref = "androidsvg" }

[bundles]
plugins = [
    "gradlePlugin-android",
    "gradlePlugin-kotlin",
    "gradlePlugin-compose"
]
test-common = [
    "kotlinx-coroutines-test",
#    "okio-fakefilesystem",
]
test-android = [
    "junit",
    "androidx-junit",
    "robolectric",
    "roborazzi-core",
    "roborazzi-junit",
    "roborazzi-compose"
]
