[versions]
agp = "8.0.0"
compose-jb = "1.4.0"
kotlin = "1.8.20"
kotlinx-coroutines = "1.6.4"
kotlinx-serialization = "1.5.0"
androidx-core-ktx = "1.10.0"
androidx-collection = "1.3.0-alpha04"
androidx-appcompat = "1.6.1"
androidx-exifinterface = "1.3.6"
spotless = "6.18.0"
ktlint = "0.48.2"
publish = "0.25.2"
moko-resources = "0.21.2"
ktor = "2.3.0"
okio = "3.3.0"
uri-kmp = "0.0.11"
napier = "2.6.1"
accompanist-drawablepainter = "0.30.0"
androidsvg = "1.4"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
composeJb = { id = "org.jetbrains.compose", version.ref = "compose-jb" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
publish = { id = "com.vanniktech.maven.publish", version.ref = "publish" }

[libraries]
gradlePlugin-android = { module = "com.android.tools.build:gradle", version.ref = "agp" }
gradlePlugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
gradlePlugin-compose = { module = "org.jetbrains.compose:compose-gradle-plugin", version.ref = "compose-jb" }

kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core-ktx" }
androidx-collection = { module = "androidx.collection:collection", version.ref = "androidx-collection" }
androidx-appcompat = { module = "androidx.appcompat:appcompat-resources", version.ref = "androidx-appcompat" }
androidx-exifinterface = { module = "androidx.exifinterface:exifinterface", version.ref = "androidx-exifinterface" }

accompanist-drawablepainter = { module = "com.google.accompanist:accompanist-drawablepainter", version.ref = "accompanist-drawablepainter" }

okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
okio-fakefilesystem = { module = "com.squareup.okio:okio-fakefilesystem", version.ref = "okio" }

ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-js = { module = "io.ktor:ktor-client-js", version.ref = "ktor" }

uri-kmp = { module = "com.eygraber:uri-kmp", version.ref = "uri-kmp" }
moko-resources = { module = "dev.icerock.moko:resources", version.ref = "moko-resources" }
napier = { module = "io.github.aakira:napier", version.ref = "napier" }
androidsvg = { module = "com.caverock:androidsvg-aar", version.ref = "androidsvg" }

[bundles]
plugins = [
    "gradlePlugin-android",
    "gradlePlugin-kotlin",
    "gradlePlugin-compose"
]
