name: Check CI

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  spotless:
    name: Spotless check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Spotless Check
        run: ./gradlew spotlessCheck --stacktrace --no-daemon --no-parallel

  lint:
    needs: spotless
    name: Gradle Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - uses: gradle/gradle-build-action@v2

      - name: Lint
        run: ./gradlew lint --stacktrace --no-daemon --no-parallel

      - name: Assemble
        run: ./gradlew assemble --stacktrace --no-daemon --no-parallel

  build:
    needs: spotless
    name: Gradle Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - uses: gradle/gradle-build-action@v2

      - name: Build
        run: ./gradlew build --stacktrace --no-daemon --no-parallel